name: flow_state
description: "Reactive abstraction to facilitate complex architectures."
version: 0.0.1
homepage: https://github.com/xbrunots/flow_state
repository: https://github.com/xbrunots/flow_state

environment:
  sdk: ^3.5.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  signals_flutter: ^5.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mockito: ^5.4.4

flutter:

